### ISSUE TITLE
Trying to link rstudio to github, but no svn executable found.

### ISSUE THREAD

**Issue by Jisu-Lim** [rocker-org/rocker-versioned#236] opened 2020-09-09 03:34 UTC
Hi, I'm using Windows 64-bit and my R version is 4.0.2.
I'm trying to link rstudio to github so I went into Tools-Global options-Git/SVN.
I can only see Git executable but no SVN executable and no SSH/RSA key.
When I try to create RSA key, it says RSA key will be created at C:/Users/?꾩???/.ssh/id_rsa, and I cannot even read the error message that pops up when I click create button cuz it's an array of ? signs.
I saw a solution in some other issue that I can solve the problem of no SVN executable by downloading  SlikSubversion so I did and designated it as a SVN, but it still doesn't work. Also, someone said I can use openssh-server package but error msg said this package cannot be installed in version 4.0.2.
Thank you

**Comment by eddelbuettel** [comment] 2020-09-09 12:41
You seem to have some general setup questions related to use of `git` and RStudio.  Maybe the book at https://happygitwithr.com/ could be of help to you?

`svn` is an alternative to `git` and was used earlier; I do not think we say that we ship the `subversion` package containing it. You could install it yourself.  Also, you do not need `openssh-server` -- the "other side" that you would want to access with `ssh` would.

Overall I do not think I see any errors reported that would be caused by our container malfunctioning or being misconfigured so I will close this.  Please reopen if you see anything wrong with the container.

**Closed by eddelbuettel** 2020-09-09 12:41 UTC
