### ISSUE TITLE
login issues with rocker/rstudio

### ISSUE THREAD

**Issue by vnijs** [rocker-org/rocker-versioned#235] opened 2020-08-29 03:57 UTC
I have been using docker with Rstudio for a few years now. Mostly it works just fine. However, disabling password now leads to the "R is taking to start than usual" message and Rstudio never comes up. I have seen this on macOS and Windows. Not tested on linux

```
docker run --rm \
  -p 127.0.0.1:8787:8787 \
  -e DISABLE_AUTH=true \
  rocker/rstudio
```

https://www.rocker-project.org/use/managing_users/

![image](https://user-images.githubusercontent.com/2998956/91627765-a446d000-e96e-11ea-8a7d-a0e4fa909591.png)

**Comment by cboettig** [comment] 2020-08-29 04:37
The most recent release of RStudio Server changed how it handles config files, so this mechanism may need revisiting...

**Comment by vnijs** [comment] 2020-08-30 19:27
I think this might be issue (https://github.com/rstudio/rstudio/issues/7575). Which is an issue listed as fixed in the 1.3.1081 preview version (https://rstudio.com/products/rstudio/download/preview-release-notes/). I have been trying out the 1.3.1081 preview version of Rstudio with docker but having no luck with authentication or getting it to launch from JupyterLab.

See also https://github.com/jupyterhub/jupyter-rsession-proxy/issues/93

**Comment by cboettig** [comment] 2020-09-24 21:35
Duplicate of https://github.com/rocker-org/rocker-versioned2/issues/78 

Try upgrading your instance to RStudio daily. e.g. launch as a bash session, upgrade and then launch:

```
docker run --rm -ti -e PASSWORD=sometest -p 8787:8787 rocker/rstudio bash
RSTUDIO_VERSION="daily" /rocker_scripts/install_rstudio.sh && /init
```

or just `docker-exec` into a running instance and run:

```
RSTUDIO_VERSION="daily" /rocker_scripts/install_rstudio.sh && /init
```

   * NOTE: requires an up-to-date rocker image pull.

**Comment by cboettig** [comment] 2020-09-24 23:26
(closing in favour of #78)

**Closed by cboettig** 2020-09-24 23:26 UTC
