### ISSUE TITLE
Incorrect or invalid username/password on macOS with M1

### ISSUE THREAD

**Issue by jakubsob** [rocker-org/rocker-versioned#257] opened 2021-04-26 10:00 UTC
Hello,

I'm trying to run RStudio image on macOS with M1 chip and this is the error I've been getting:

![Screenshot 2021-04-26 at 11 51 24](https://user-images.githubusercontent.com/37193264/116063930-d3404d80-a685-11eb-8bc0-a0fad14b7b8a.png)

I'm setting up a trivial user name and password to make sure I make no mistakes when typing it in, but using other names give the same error.

```
➜  ~ docker run --rm -d -p 8787:8787 -e PASSWORD=x -e USER=x --platform linux/amd64 rocker/rstudio   
```

I've tried out few rstudio image versions and I've been getting the same error every time. r-ver image as well as any other I've tried works seamlessly so I think it may be an issue with this particular image.

I've installed docker from [docker page](https://docs.docker.com/docker-for-mac/apple-silicon/).

```
➜  ~ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64 (rosetta)
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:48 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Do you know what might be the issue here? 
Thanks

**Comment by cboettig** [comment] 2021-04-26 22:58
Seems to be a problem related to the ARM architecture: https://github.com/rocker-org/rocker-versioned2/issues/144.  May require following up with the RStudio team...

**Comment by paupaiz** [comment] 2021-11-28 01:32
having same issue here on M1... please let me know what information would be helpful to provide

**Comment by cboettig** [comment] 2021-11-29 04:55
@paupaiz as noted above, RStudio Server does not support ARM architecture at this time.  Please keep an eye on https://github.com/rstudio/rstudio/issues/8809

**Comment by eitsupi** [comment] 2022-02-26 14:11
Duplicate of rocker-org/rocker-versioned2#144

**Closed** 2022-02-26 14:11 UTC
