### ISSUE TITLE
shorter image versions

### ISSUE THREAD

**Issue by robkooper** [rocker-org/rocker-versioned#211] opened 2020-04-29 01:51 UTC
I was using the 3.6 image, assuming this would be the latest image of 3.6, but as it turns out this is the 3.6.0 image. I was wondering if it is possible to use 3.6 for the latest version of 3.6 (e.g. 3.6.3).

**Comment by cboettig** [comment] 2020-05-01 00:44
@robkooper apologies, yes we used to have a few docker hub build triggers that would publish the short-image tags, but had some issues with docker hub deploys and have dropped those about the time that 3.6.0 was `latest`...

We could add them back with our new deploy system.  We're introducing a few more flavors of tags already though (e.g. for ML images that may need specific versions of CUDA as well as R) so I'm a bit on the fence about having too many tags (especially if they are the same thing).  Will leave this open for further discussion and we'll dry and clarify better in the documentation.  Thanks!

**Comment by cboettig** [comment] 2020-09-25 03:08
duplicate of https://github.com/rocker-org/rocker/issues/349

**Closed by cboettig** 2020-09-25 03:08 UTC
