### ISSUE TITLE
Is there a way to use pyenv in Rocker Rstudio

### ISSUE THREAD

**Issue by donnrri** [rocker-org/rocker-versioned#232] opened 2020-08-06 08:47 UTC
Hello

I hope you can assist me.  I have an RStudio project that uses Python and have to set up virtual environment for it in a Docker (rocker/verse) container.  Why , because the RStudio application uses a python script which subsequently calls a Linux complied executable. 

I do not have a linux machine so am using Docker to allow this to be called. I hope that makes some sort of sense.

I have the following Dockerfile using the rocker/verse image 

From rocker/verse:latest

MAINTAINER Me me@me.co.uk

COPY stuff /home/guest/r-docker

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        curl \
        git \
        libbz2-dev \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        llvm \
        make \
        tk-dev \
        wget \
        xz-utils \
        zlib1g-dev

RUN curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer \
    | bash

ENV PATH=$HOME/.pyenv/bin:$PATH

WORKDIR ~/

RUN echo 'export PATH="/root/.pyenv/bin:$PATH"' >> .bashrc

RUN echo 'eval "$(pyenv init -)"' >> .bashrc

RUN echo 'eval "$(pyenv virtualenv-init -)"' >> .bashrc

RUN /bin/bash -c 'source .bashrc '

#Install nano (optional)

RUN apt-get install nano

RUN export VISUAL=nano

RUN export EDITOR="$VISUAL"

In an interactive session , using docker exec ,  I can use "which pyenv" to see pyenv is installed /root/.pyenv/bin/pyenv

But as I understand it , RStudio runs as guest (or using ROOT=TRUE as a sudo user) , which means when the python script is called, the pyenv cannot be found. 

I get errors

sh: 9:my_bash.bash: pyenv: not found

Is there anyway to allow the RStudio to use the pyenv installed .  I apologise for my description , I hope it makes sense, I am not so experienced with virtual environments and Rocky/verse images and so on.

**Comment by cboettig** [comment] 2020-08-06 19:48
I think the problem is that you have not updated environmental variables in `.Renviron`.  For whatever reason, RStudio has chosen not to simply read the user's environment variables, but declares all it's own variables.  In particular, you probably have to set `PATH`.  i.e. from inside the RStudio R console, try Sys.getenv("PATH") and see if `pyenv` is on path?  

You should also be able to confirm things work in the RStudio bash terminal too.  

(Aside, but can you give more context?  Is your goal to use multiple different versions of python from the same session?)

**Comment by eitsupi** [comment] 2022-02-26 14:34
Close the issue due to lack of information. If a similar problem occurs again, please open a new issue at https://github.com/rocker-org/rocker-versioned2.

**Closed by eitsupi** 2022-02-26 14:34 UTC
